### ISSUE TITLE
Validator rules method inconsistent with parent

### ISSUE THREAD

**Issue by ahuininga** [realpage/json-api-for-lumen#15]
In the readme it says you can add rules to your validator with the following code

```php
public function rules() : array
    {
        return parent::rules([
            'data.attributes.name' => 'required',
        ]);
    }
    
    public function messages() : array
    {
        return parent::messages([
            'data.attributes.name.required' => 'A name is required',
        ]);
    }
```

But the rules method in RealPage\JsonApi\Validation\ValidatesRequests doesn't except any parameters.

Should the rules method in RealPage\JsonApi\Validation\ValidatesRequests accept an array as an parameter and merge the array with the default rules?

**Comment by bkuhl** [comment]
The README related to this appears to be out of date

**Comment by bkuhl** [comment]
Documentation has been updated.

**Comment by ahuininga** [comment]
👍 But i noticed a copy/paste error. The second one should merge messages instead of rules

```php
public function messages() : array
    {
        return array_merge(parent::rules(), 
            'data.attributes.name.required' => 'A name is required',
        ]);
    }
```
