### ISSUE TITLE
Could PHP 7.1 requirement been dropped?

### ISSUE THREAD

**Issue by jelhan** [realpage/json-api-for-lumen#16]
Your composer.json requires at least php 7.1. I've tested against php 7.0 and all test are passing. Is php 7.1 really required? This was introduced here: 329fa0ba898acfa5401d139f93df36a3d1364aa2

**Comment by bkuhl** [comment]
Yes, it looks like the travis configuration has been using 7.0 all along.  I'm updating this here: https://github.com/realpage/json-api-for-lumen/pull/17
