### ISSUE TITLE
Required accept header

### ISSUE THREAD

**Issue by jlaswell** [realpage/json-api-for-lumen#4]
The `Accept` header is required to have a value of `application/vnd.api+json` while the spec states:

> Clients that include the JSON API media type in their Accept header MUST specify the media type there at least once without any media type parameters.

This means that the client should be able to make requests without the requirement of specifying an `Accept` value.

**Comment by jelhan** [comment]
As far as I understand json api specification it does not make any statement about how a server should behave if client does not send an `Accept` header. What you have quoted is just about media type parameters. Have a deeper look to the context of these requirement: http://jsonapi.org/format/#content-negotiation

HTTP/1.1 specification (RFC 7231) clears out what to do if there is no `Accept` header at all:
> 5.3.2. Accept
> [...]
> A request without any Accept header field implies that the user agent will accept any media type in response. If the header field is present in a request and none of the available representations for the response have a media type that is listed as acceptable, the origin server can either honor the header field by sending a 406 (Not Acceptable) response or disregard the header field by treating the response as if it is not subject to content negotiation.

So to follow that specification it would be nice if `json-api-for-lumen` allows per configuration
- to send `406 (Not Acceptable)` if `Accept` header is not `application/vnd.api+json`. (current implementation)
- to send `406 (Not Acceptable)` if `Accept` header is present but is not `application/vnd.api+json` and respond with json api document in all other cases.
- to ignore `Accept` header at all and respond to all requests with json api document.

Following the HTTP/1.1 specification and what user would expect I would recommend to have second option as default.
